<a href="https://colab.research.google.com/github/bhatiaparteek/ml_with_python/blob/main/Chapter_8_Multiple_Linear_Regression/chapter_8_multiple_linear_regression_Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Step 1: Importing the Libraries

In [1]:
# 1. Importing the Libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

Step 2: Load the dataset

This will open a file selection dialog. Choose your 50_AdAgency.csv file (get this from GitHub repo) and upload it.

In [2]:
from google.colab import files

# Upload the file from your local system
uploaded = files.upload()

Saving 50_AdAgency.csv to 50_AdAgency.csv


In [16]:
# Load the dataset
dataset = pd.read_csv('50_AdAgency.csv')
print(dataset.head())

   Print Media Expenses  Social Media Expenses  Outdoor Ad Expenses  \
0             165349.20              136897.80            471784.10   
1             162597.70              151377.59            443898.53   
2             153441.51              101145.55            407934.54   
3             144372.41              118671.85            383199.62   
4             142107.34               91391.77            366168.42   

         City     Profit  
0      Mumbai  192261.83  
1  Chandigarh  191792.06  
2       Delhi  191050.39  
3      Mumbai  182901.99  
4       Delhi  166187.94  


Step 3: Creating Data Frames

In [17]:
# Step 3: Creating Data Frames
X = dataset.iloc[:, :-1].values
Y = dataset.iloc[:, 4].values
print(X)
print(Y)

[[165349.2 136897.8 471784.1 'Mumbai']
 [162597.7 151377.59 443898.53 'Chandigarh']
 [153441.51 101145.55 407934.54 'Delhi']
 [144372.41 118671.85 383199.62 'Mumbai']
 [142107.34 91391.77 366168.42 'Delhi']
 [131876.9 99814.71 362861.36 'Mumbai']
 [134615.46 147198.87 127716.82 'Chandigarh']
 [130298.13 145530.06 323876.68 'Delhi']
 [120542.52 148718.95 311613.29 'Mumbai']
 [123334.88 108679.17 304981.62 'Chandigarh']
 [101913.08 110594.11 229160.95 'Delhi']
 [100671.96 91790.61 249744.55 'Chandigarh']
 [93863.75 127320.38 249839.44 'Delhi']
 [91992.39 135495.07 252664.93 'Chandigarh']
 [119943.24 156547.42 256512.92 'Delhi']
 [114523.61 122616.84 261776.23 'Mumbai']
 [78013.11 121597.55 264346.06 'Chandigarh']
 [94657.16 145077.58 282574.31 'Mumbai']
 [91749.16 114175.79 294919.57 'Delhi']
 [86419.7 153514.11 0.0 'Mumbai']
 [76253.86 113867.3 298664.47 'Chandigarh']
 [78389.47 153773.43 299737.29 'Mumbai']
 [73994.56 122782.75 303319.26 'Delhi']
 [67532.53 105751.03 304768.73 'Delhi']

Step 4: Label Encoding

In [18]:
# Step 4: Label Encoding
from sklearn.preprocessing import LabelEncoder
labelencoder = LabelEncoder()
X[:, 3] = labelencoder.fit_transform(X[:, 3])
print(X)

[[165349.2 136897.8 471784.1 2]
 [162597.7 151377.59 443898.53 0]
 [153441.51 101145.55 407934.54 1]
 [144372.41 118671.85 383199.62 2]
 [142107.34 91391.77 366168.42 1]
 [131876.9 99814.71 362861.36 2]
 [134615.46 147198.87 127716.82 0]
 [130298.13 145530.06 323876.68 1]
 [120542.52 148718.95 311613.29 2]
 [123334.88 108679.17 304981.62 0]
 [101913.08 110594.11 229160.95 1]
 [100671.96 91790.61 249744.55 0]
 [93863.75 127320.38 249839.44 1]
 [91992.39 135495.07 252664.93 0]
 [119943.24 156547.42 256512.92 1]
 [114523.61 122616.84 261776.23 2]
 [78013.11 121597.55 264346.06 0]
 [94657.16 145077.58 282574.31 2]
 [91749.16 114175.79 294919.57 1]
 [86419.7 153514.11 0.0 2]
 [76253.86 113867.3 298664.47 0]
 [78389.47 153773.43 299737.29 2]
 [73994.56 122782.75 303319.26 1]
 [67532.53 105751.03 304768.73 1]
 [77044.01 99281.34 140574.81 2]
 [64664.71 139553.16 137962.62 0]
 [75328.87 144135.98 134050.07 1]
 [72107.6 127864.55 353183.81 2]
 [66051.52 182645.56 118148.2 1]
 [65605.48 153032.0

Step 5: One-hot encoding categorical attribute

In [19]:
# Step 5: One-hot encoding categorical attribute
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [3])], remainder='passthrough')
X = np.array(ct.fit_transform(X))
print(X)

[[0.0 0.0 1.0 165349.2 136897.8 471784.1]
 [1.0 0.0 0.0 162597.7 151377.59 443898.53]
 [0.0 1.0 0.0 153441.51 101145.55 407934.54]
 [0.0 0.0 1.0 144372.41 118671.85 383199.62]
 [0.0 1.0 0.0 142107.34 91391.77 366168.42]
 [0.0 0.0 1.0 131876.9 99814.71 362861.36]
 [1.0 0.0 0.0 134615.46 147198.87 127716.82]
 [0.0 1.0 0.0 130298.13 145530.06 323876.68]
 [0.0 0.0 1.0 120542.52 148718.95 311613.29]
 [1.0 0.0 0.0 123334.88 108679.17 304981.62]
 [0.0 1.0 0.0 101913.08 110594.11 229160.95]
 [1.0 0.0 0.0 100671.96 91790.61 249744.55]
 [0.0 1.0 0.0 93863.75 127320.38 249839.44]
 [1.0 0.0 0.0 91992.39 135495.07 252664.93]
 [0.0 1.0 0.0 119943.24 156547.42 256512.92]
 [0.0 0.0 1.0 114523.61 122616.84 261776.23]
 [1.0 0.0 0.0 78013.11 121597.55 264346.06]
 [0.0 0.0 1.0 94657.16 145077.58 282574.31]
 [0.0 1.0 0.0 91749.16 114175.79 294919.57]
 [0.0 0.0 1.0 86419.7 153514.11 0.0]
 [1.0 0.0 0.0 76253.86 113867.3 298664.47]
 [0.0 0.0 1.0 78389.47 153773.43 299737.29]
 [0.0 1.0 0.0 73994.56 122782.75 3

Step 6: Avoiding the Dummy Variable Trap

In [20]:
# Step 6: Avoiding the Dummy Variable Trap
X = X[:, 1:]
print(X)

[[0.0 1.0 165349.2 136897.8 471784.1]
 [0.0 0.0 162597.7 151377.59 443898.53]
 [1.0 0.0 153441.51 101145.55 407934.54]
 [0.0 1.0 144372.41 118671.85 383199.62]
 [1.0 0.0 142107.34 91391.77 366168.42]
 [0.0 1.0 131876.9 99814.71 362861.36]
 [0.0 0.0 134615.46 147198.87 127716.82]
 [1.0 0.0 130298.13 145530.06 323876.68]
 [0.0 1.0 120542.52 148718.95 311613.29]
 [0.0 0.0 123334.88 108679.17 304981.62]
 [1.0 0.0 101913.08 110594.11 229160.95]
 [0.0 0.0 100671.96 91790.61 249744.55]
 [1.0 0.0 93863.75 127320.38 249839.44]
 [0.0 0.0 91992.39 135495.07 252664.93]
 [1.0 0.0 119943.24 156547.42 256512.92]
 [0.0 1.0 114523.61 122616.84 261776.23]
 [0.0 0.0 78013.11 121597.55 264346.06]
 [0.0 1.0 94657.16 145077.58 282574.31]
 [1.0 0.0 91749.16 114175.79 294919.57]
 [0.0 1.0 86419.7 153514.11 0.0]
 [0.0 0.0 76253.86 113867.3 298664.47]
 [0.0 1.0 78389.47 153773.43 299737.29]
 [1.0 0.0 73994.56 122782.75 303319.26]
 [1.0 0.0 67532.53 105751.03 304768.73]
 [0.0 1.0 77044.01 99281.34 140574.81]
 [0

Step 7: Dataset Split

In [22]:
# Step 7: Dataset Split
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=0)
print(X_train)
print(X_test)
print(Y_train)
print(Y_test)

[[1.0 0.0 55493.95 103057.49 214634.81]
 [0.0 1.0 46014.02 85047.44 205517.64]
 [1.0 0.0 75328.87 144135.98 134050.07]
 [0.0 0.0 46426.07 157693.92 210797.67]
 [1.0 0.0 91749.16 114175.79 294919.57]
 [1.0 0.0 130298.13 145530.06 323876.68]
 [1.0 0.0 119943.24 156547.42 256512.92]
 [0.0 1.0 1000.23 124153.04 1903.93]
 [0.0 1.0 542.05 51743.15 0.0]
 [0.0 1.0 65605.48 153032.06 107138.38]
 [0.0 1.0 114523.61 122616.84 261776.23]
 [1.0 0.0 61994.48 115641.28 91131.24]
 [0.0 0.0 63408.86 129219.61 46085.25]
 [0.0 0.0 78013.11 121597.55 264346.06]
 [0.0 0.0 23640.93 96189.63 148001.11]
 [0.0 0.0 76253.86 113867.3 298664.47]
 [0.0 1.0 15505.73 127382.3 35534.17]
 [0.0 1.0 120542.52 148718.95 311613.29]
 [0.0 0.0 91992.39 135495.07 252664.93]
 [0.0 0.0 64664.71 139553.16 137962.62]
 [0.0 1.0 131876.9 99814.71 362861.36]
 [0.0 1.0 94657.16 145077.58 282574.31]
 [0.0 0.0 28754.33 118546.05 172795.67]
 [0.0 0.0 0.0 116983.8 45173.06]
 [0.0 0.0 162597.7 151377.59 443898.53]
 [1.0 0.0 93863.75 1273

Step 8: Model Building

In [23]:
# Step 8: Model Building
from sklearn.linear_model import LinearRegression
linear_regressor = LinearRegression()
linear_regressor.fit(X_train, Y_train)

LinearRegression()

Step 9: Predictions

In [26]:
# Step 9: Predictions
Y_pred = linear_regressor.predict(X_test)
print('predicted values',Y_pred)
print('actual values',Y_test)

predicted values [103015.20159796 132582.27760816 132447.73845175  71976.09851259
 178537.48221054 116161.24230163  67851.69209676  98791.73374688
 113969.43533012 167921.0656955 ]
actual values [103282.38 144259.4  146121.95  77798.83 191050.39 105008.31  81229.06
  97483.56 110352.25 166187.94]


Step 10: Model Evaluation

In [27]:
# Step 10: Model Evaluation
from sklearn import metrics

# Evaluating the model and printing the value of MAE
print('Mean Absolute Error')
print(metrics.mean_absolute_error(Y_test, Y_pred))

# Evaluating the model and printing the value of MSE
print('Mean Square Error')
print(metrics.mean_squared_error(Y_test, Y_pred))

# Evaluating the model and printing the value of RMSE
print('Root Mean Square Error')
print(np.sqrt(metrics.mean_squared_error(Y_test, Y_pred)))


Mean Absolute Error
7514.293659636814
Mean Square Error
83502864.03250548
Root Mean Square Error
9137.990152791011
